services:
  - type: web
    name: outcast-ranking
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: outcast-ranking-db
          property: connectionString

databases:
  - name: outcast-ranking-db
    databaseName: outcast_ranking
    user: outcast_user
    plan: free
